# Root Application (App of Apps Pattern)
# This is the single entry point for all ArgoCD-managed resources
# Apply this once to bootstrap the entire GitOps infrastructure
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Matchpoint-AI/matchpoint-github-runners-helm
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: true
      # Include all YAML files in the apps directory
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Ignore differences that are expected in ApplicationSet status
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
