# Default values for github-actions-controller
# This is a YAML-formatted file.

# Override values for the GitHub Actions Runner Scale Set Controller
gha-runner-scale-set-controller:
  # Controller configuration
  replicaCount: 1

  image:
    repository: ghcr.io/actions/gha-runner-scale-set-controller
    tag: "0.12.1"
    pullPolicy: IfNotPresent

  # Service account
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532

  # Security context for container
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

  # Resources
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # Node selector
  nodeSelector: {}

  # Tolerations
  tolerations: []

  # Affinity
  affinity: {}

  # Controller manager args
  args:
    - --auto-scaling-runner-set-only
    - --log-level=debug
    - --log-format=text
    - --runner-max-concurrent-reconciles=2
    - --update-strategy=immediate
    - --listener-metrics-addr=0
    - --listener-metrics-endpoint=
    - --metrics-addr=0