apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-api-runners-v2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Matchpoint-AI/matchpoint-github-runners-helm
    targetRevision: main
    path: charts/github-actions-runners
    helm:
      releaseName: arc-api-runners-v2
      valueFiles:
        - ../../examples/api-runners-values.yaml
      # GitHub token should be configured as a secret in the cluster
      # kubectl create secret generic github-runner-token -n arc-api-runners-v2 --from-literal=github_token=YOUR_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-api-runners-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: arc-api-runners-v2-gha-rs-github-secret
      jsonPointers:
        - /data/github_token