apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-beta-runners-new
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Matchpoint-AI/matchpoint-github-runners-helm
    targetRevision: main
    path: charts/github-actions-runners
    helm:
      releaseName: arc-beta-runners-new
      valueFiles:
        - ../../examples/beta-runners-values.yaml
      # GitHub token should be configured as a secret in the cluster
      # kubectl create secret generic github-runner-token -n arc-beta-runners-new --from-literal=github_token=YOUR_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-beta-runners-new
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m