apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Matchpoint-AI/matchpoint-github-runners-helm
    targetRevision: main
    path: charts/github-actions-runners
    helm:
      # CRITICAL: releaseName MUST match runnerScaleSetName in values file
      # See: https://github.com/Matchpoint-AI/matchpoint-github-runners-helm/issues/89
      # Using arc-runners to match existing deployment and frontend workflows
      releaseName: arc-runners
      valueFiles:
        - ../../examples/runners-values.yaml
      # GitHub token should be configured as a secret in the cluster
      # kubectl create secret generic github-runner-token -n arc-runners --from-literal=github_token=YOUR_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # Ignore github secrets to prevent token leakage in diffs
    # NOTE: Secret names follow pattern: {releaseName}-gha-rs-github-secret
    - group: ""
      kind: Secret
      name: arc-runners-gha-rs-github-secret
      jsonPointers:
        - /data/github_token